- app/views/admins/cds/create.html.erb
- app/views/admins/cds/destroy.html.erb
- app/views/admins/cds/update.html.erb
- app/views/admins/clients/destroy.html.erb
- app/views/admins/clients/update.html.erb
- app/views/admins/orders/update.html.erb
- app/views/clients/clients/update.html.erb
- app/views/clients/items/add_item.html.erb
- app/views/clients/items/destroy.html.erb
- app/views/clients/items/update.html.erb
不要なビューまで作成されてしまっていたので、削除して整理しました！
> [delete views]

- app/models/address.rb
- app/models/artist.rb
- app/models/cd.rb
- app/models/client.rb
- app/models/disc.rb
- app/models/genre.rb
- app/models/item.rb
- app/models/label.rb
- app/models/order.rb
- app/models/order_item.rb
- app/models/song.rb
> [add relation]

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/clients/items_controller.rb
- app/views/clients/items/edit.html.erb
- config/routes.rb
・gemの'bootstrap'、'j-query-rails'の追加
・application.cssとapplication.jsに上記に付随する必要事項を追記
・clients_items_controllerに機能を追加
・clients_items_editの簡易ビューの作成
> [add_gem][modified_items_controller][modified_items_view]

- app/controllers/application_controller.rb
- app/models/client.rb
- app/views/admins/sessions/new.html.erb
- app/views/clients/registrations/new.html.erb
- app/views/clients/sessions/new.html.erb
- config/routes.rb
> [add]login

- app/controllers/admins/clients_controller.rb
- app/views/admins/clients/index.html.erb
・adminの顧客一覧ページを作成
しました！ご確認お願いします！
> [add admins_clients_index]

- app/views/layouts/application.html.erb
・application.html.erbにログイン済みクライアント、ログインしてない人、アドミンの3パターンに分けてヘッダーを追加しました。
（検索機能はまだ付けれていないので、簡易的に文字で表示してます）
ご確認お願いします！
> [add header]

- app/controllers/admins/cds_controller.rb
- app/models/cd.rb
- app/models/label.rb
- app/views/admins/cds/list.html.erb
- app/views/admins/cds/new.html.erb
- db/seeds.rb
まだCD新規登録を記述中ですが、確認お願いします。
やったことは下記に記します。
・各種入力フォームの搭載
・dbから情報を持ってくるタイプのプルダウン（レーベルはseed）
・ステータスのenum化
> cd_new_create

- app/controllers/application_controller.rb
- app/controllers/clients/clients_controller.rb
- app/views/clients/clients/show.html.erb
- app/views/clients/registrations/new.html.erb
> Mypage clients

- app/controllers/admins/clients_controller.rb
- app/controllers/application_controller.rb
- app/controllers/clients/cds_controller.rb
- app/views/admins/clients/index.html.erb
- app/views/clients/cds/search.html.erb
・検索結果のviewとadmin.clinentsの一覧ページのviewにペジネーションを追加しました！
> [add_pagination]

- Gemfile
- Gemfile.lock
- app/controllers/clients/clients_controller.rb
- app/views/clients/clients/edit.html.erb
- app/views/clients/clients/show.html.erb
- app/views/clients/registrations/new.html.erb
- config/routes.rb
クライアントのshow,editを作成しました。
[show]
登録住所の部分はまだコードを書いてません、ワイヤーフレームの部分を参照して分けてあります。
退会の所は、ひと段落してからやるのでgemのインストールなどあとで追加予定です。
[edit]
パスワードの編集部分を消しました、この部分はチームで相談する必要があります。
> Mypage clients3

- app/controllers/admins/clients_controller.rb
- app/controllers/clients/clients_controller.rb
- app/views/admins/clients/edit.html.erb
- app/views/admins/clients/show.html.erb
管理者側の顧客詳細、編集を作成しました。
一通り試してちゃんと管理者側から編集できたりクライアント側から変更が確認できたりしたので、
プルリクしました。
> [create]show,edit

- app/controllers/clients/orders_controller.rb
- app/views/clients/clients/new.html.erb
- app/views/clients/clients/show.html.erb
- app/views/clients/orders/buy.html.erb
- app/views/clients/orders/index.html.erb
- config/application.rb
- config/routes.rb
実際にカートにアイテムを入れて購入するとエラーが発生したので修正しました。
・item.priceの部分をすべてitem.cd.priceに修正しました。
・order_item.purchased_priceのpurchasedがpuchasedになっていたので修正しました。
＜確認＞itemsテーブルのデータはそれぞれ別のorder_itemsテーブルのレコードに保存されていることを確認しました。＜確認＞
> fix purchase action

- Gemfile
- Gemfile.lock
- app/controllers/admins/clients_controller.rb
- app/controllers/clients/clients_controller.rb
- app/views/admins/clients/index.html.erb
- app/views/admins/clients/show.html.erb
- app/views/clients/clients/new.html.erb
- app/views/clients/clients/show.html.erb
- app/views/clients/registrations/new.html.erb
- config/routes.rb
住所新規登録を追加しました、管理者側だけ住所の削除リンクはつけませんでした。
自己判断なのでつけたほうがよければ言ってください。
> クライアントと管理者側の新規住所登録表示

- app/controllers/clients/items_controller.rb
- app/views/clients/cds/index.html.erb
- app/views/clients/cds/show.html.erb
- app/views/clients/items/index.html.erb
- app/views/layouts/application.html.erb
・items controllerのadd_itemアクションに、在庫以上の数が入力された際の処理と、マイナスの数を打てないように調整。
・cds一覧にて、画像ファイルにリンク先を追加。
・ヘッダー下に、flashの作成。
・カート編集ページに購入確定画面へのリンクを追加。
ご確認よろしくお願いします！
> Cart function 2

- app/views/admins/clients/show.html.erb
> add_delete

- app/controllers/admins/cds_controller.rb
- app/views/admins/cds/index.html.erb
- app/views/admins/cds/show.html.erb
- app/views/clients/cds/search.html.erb
- app/views/clients/cds/show.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
・client/adminそれぞれでのrootの設定
・検索結果のCDイメージの追加
・adminsのcdのindexページ、showページの追加
ご確認宜しくお願いいたします！
> [modified_some_stuffs]

- app/controllers/clients/clients_controller.rb
- app/views/clients/clients/edit.html.erb
- app/views/clients/clients/show.html.erb
- app/views/clients/passwords/edit.html.erb
- app/views/clients/passwords/new.html.erb
- app/views/clients/sessions/new.html.erb
- config/application.rb
- config/locales/devise.ja.yml
- config/routes.rb
クライアントコントローラのupdateアクションにコードを新しく記載したらできました。
まだ未完成ですがお願いします
> マイページにパスワード変更のフォームを作りました

- app/assets/stylesheets/application.scss
- app/controllers/admins/cds_controller.rb
- app/views/admins/cds/_disc_fields.html.erb
- app/views/admins/cds/_form.html.erb
- app/views/admins/cds/_song_fields.html.erb
> new_cd_tabletag

- app/controllers/clients/items_controller.rb
- app/models/cd.rb
- app/views/clients/items/index.html.erb
- app/views/layouts/application.html.erb
・ヘッダー関連の見た目を整理しました！
・カート内で在庫を超える商品の変更をしようとした時にエラーメッセージを出して、先に進めなくなるように変更しました。
ご確認宜しくお願いします！
> On trial 3

- app/views/admins/cds/_editform.html.erb
- app/views/admins/cds/edit.html.erb
> edit_cd add-song

- app/controllers/admins/cds_controller.rb
- app/views/admins/cds/show.html.erb
- app/views/clients/cds/show.html.erb
・admins/cleintsのcdsのshowのviewに、曲順を追加しました！
・adminsのcdコントローラーのstrong parameterのimage_idをimageに変更しました！
ご確認よろしくお願いします！
> [modified]

- app/controllers/clients/items_controller.rb
- app/views/clients/clients/show.html.erb
- app/views/clients/items/index.html.erb
- app/views/layouts/application.html.erb
・カート機能の問題点の修正。
・検索機能、空の状態で検索できないように変更。
・マイページのshowのviewにて、サブアドレスがある人とない人で表示を変更。
ご確認宜しくお願いします！
> [modified_functions]

- app/controllers/admins/sessions_controller.rb
- app/controllers/application_controller.rb
- app/controllers/clients/sessions_controller.rb
- app/models/cd.rb
- app/views/admins/cds/_editform.html.erb
- app/views/admins/cds/_newform.html.erb
- app/views/admins/cds/_song_fields.html.erb
- app/views/admins/cds/edit.html.erb
- app/views/admins/cds/new.html.erb
ログイン先の遷移先を変更しました
1. 管理者ログイン　→　管理者側の商品一覧
2. エンドユーザログイン　→　エンドユーザ側の商品一覧
> admins rework login

- app/assets/stylesheets/admins/cds.scss
- app/assets/stylesheets/admins/clients.scss
- app/assets/stylesheets/admins/orders.scss
- app/assets/stylesheets/clients/orders.scss
- app/views/admins/cds/index.html.erb
- app/views/admins/clients/index.html.erb
- app/views/admins/clients/show.html.erb
- app/views/admins/orders/index.html.erb
- app/views/clients/cds/search.html.erb
- app/views/clients/orders/index.html.erb
履歴一覧から正しい詳細ページに遷移していなかったので、修正しました。
・item.idを指定しました。
> orders to show

- Gemfile
- Gemfile.lock
- app/controllers/admins/cds_controller.rb
- app/models/cd.rb
- app/models/disc.rb
- app/models/song.rb
- app/views/admins/cds/_error_messages.html.erb
- app/views/admins/cds/_newform.html.erb
- app/views/admins/cds/edit.html.erb
- app/views/admins/cds/new.html.erb
- app/views/admins/clients/show.html.erb
- config/application.rb
- config/locales/models/ja.yml
下記に記載したことを変更追加しました
・CDの新規登録時、編集時に空欄のままだとエラー文出るようにした
・エラー文が日本語になるようにgemを１つ追加しました
> new_cds error

- app/assets/stylesheets/application.css.scss
> add conflict

- app/assets/stylesheets/clients/cds.scss
- app/views/clients/cds/show.html.erb
> add_cds_show

- app/controllers/admins/cds_controller.rb
- app/views/admins/cds/index.html.erb
> cd-rework link

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/clients/cds.scss
- app/assets/stylesheets/clients/clients.scss
- app/assets/stylesheets/clients/items.scss
- app/views/clients/cds/index.html.erb
- app/views/clients/clients/show.html.erb
- app/views/clients/items/index.html.erb
- app/views/layouts/application.html.erb
ローディング画面の作成とマイぺージとカート画面のcssを整えました
> create loading view

- app/assets/stylesheets/clients/orders.scss
- app/views/clients/orders/buy.html.erb
- app/views/clients/orders/index.html.erb
- app/views/clients/orders/purchase.html.erb
- app/views/clients/orders/show.html.erb
- app/views/layouts/application.html.erb
・client側、注文確認画面のレイアウトを直しました！
ご確認お願いします！
> [modified_design]

- app/views/layouts/application.html.erb
> little form

- app/assets/stylesheets/application.scss
- app/views/clients/orders/index.html.erb
- app/views/layouts/application.html.erb
・各ページのviewページを修正しました！
宜しくお願いします！
> [modified_details]

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
エラーメッセージ、サクセスメッセージの表記を編集しました！
お願いします！
> [edit_error_messages]

- db/seeds.rb
シードデータ 、途中までですが、あげときます！
ご確認よろしくお願いします！
> [add_seed_2]

- app/views/clients/cds/show.html.erb
クライアント側の
商品詳細のカート追加ボタンに色をつけました。
> add_button

- app/assets/stylesheets/clients/orders.scss
- app/controllers/clients/clients_controller.rb
- app/views/admins/cds/_disc_fields.html.erb
- app/views/admins/cds/_editform.html.erb
- app/views/admins/cds/_newform.html.erb
- app/views/admins/cds/_song_fields.html.erb
- app/views/admins/orders/index.html.erb
- app/views/clients/orders/index.html.erb
> history-rework

- app/assets/stylesheets/clients/orders.scss
- app/views/clients/orders/buy.html.erb
> edit_buypage

- app/assets/stylesheets/application.scss
- app/controllers/admins/clients_controller.rb
- app/controllers/admins/orders_controller.rb
- app/controllers/clients/orders_controller.rb
- app/views/admins/clients/index.html.erb
- app/views/admins/clients/show.html.erb
- app/views/admins/orders/index.html.erb
- app/views/clients/clients/show.html.erb
- app/views/clients/orders/index.html.erb
- config/locales/models/ja.yml
> histroy-kaminari

- app/controllers/admins/clients_controller.rb
- app/controllers/admins/orders_controller.rb
- app/controllers/clients/orders_controller.rb
> [modified_paginate]

- app/controllers/clients/items_controller.rb
- app/models/admin.rb
> [modified_test]

- app/views/clients/cds/show.html.erb
商品ステータスが販売停止中の際に、カートに追加ボタンを非表示にしました！
お願いします！
> [modified_cart_function_3]

- app/views/clients/cds/show.html.erb
- app/views/clients/orders/buy.html.erb
> [modified_test_5]

- config/routes.rb
adminの登録画面に誰でも入れてしまうのを、修正しました！
お願いします！
> [modified_admin_registeration]

- app/assets/stylesheets/application.scss
- app/views/clients/orders/buy.html.erb
- app/views/layouts/application.html.erb
> addres-rework

- app/views/admins/cds/index.html.erb
- app/views/clients/cds/index.html.erb
> [add_last]
